name: test-publish

on:
  workflow_dispatch:
    inputs:
      mark:
        description: 发布说明
        required: true
        default: ''

jobs:
  build:
    name: 构建打包
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: |
          echo 发布说明: ${{ github.event.inputs.mark }}
      - run: |
          pwd
          ls
          cd ..
          ls
          node -v
          npm -v
          npm config get registry
          
  publish-npm:
    name: 发布到npm
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: |
          npm token list --json
      - env:
          NPM_TOKEN: ${{secrets.npm_token}}

