name: test-publish

on:
  workflow_dispatch:
    inputs:
      mark:
        description: '发布备注'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: |
          pwd
          ls
          cd ..
          ls
          node -v
          npm -v
          npm config get registry
      - run: | 
          echo "Marks ${{ github.event.inputs.mark }}!"
          echo "你妹的，可以子"
        

